# Generated by Django 3.2.5 on 2021-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
