# Generated by Django 3.2.5 on 2021-08-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='breed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
