# Generated by Django 3.2.5 on 2021-08-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20210725_2234'),
        ('profiles', '0003_alter_userprofile_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='default_age',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='default_description',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='breed',
            new_name='default_location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='default_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed'),
        ),
    ]
