# Generated by Django 3.2.5 on 2021-08-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210802_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_breed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
