# Generated by Django 3.2.5 on 2021-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_default_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_breed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_street_address1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
