# Generated by Django 3.2.5 on 2021-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='member_number',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='user',
        ),
        migrations.AddField(
            model_name='dog',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
