# Generated by Django 3.2.5 on 2021-07-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='Breed',
            new_name='breed',
        ),
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
