# Generated by Django 3.2.5 on 2021-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20210807_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
